// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwzbgsdsdfxfbdodmqdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3emJnc2RzZGZ4ZmJkb2RtcWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTgxNzgsImV4cCI6MjA3MDg3NDE3OH0._g-qBhXxuRD4Ojv8LZg_8tNpAciTkPWpX-TihId4cts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});